version: 2
update_configs:
  - package_manager: "pip"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    default_labels:
      - "dependencies"
    allowed_updates:
      - match:
          update_type: "all"
    version_requirement_updates: "increase_versions"