blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/Zund4m0n/blackhat/discussions
    about: Please ask and answer questions here.
  - name: Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
