name: Feature Request
description: Request a new feature or enhancement
title: "[Feature Request]: "
labels: ["feature", "enhancement", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a feature request! Please fill out the information below.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more information?
      placeholder: e.g., email@example.com
    validations:
      required: false
  - type: textarea
    id: what-feature
    attributes:
      label: What feature do you want to request?
      description: Please describe the new feature or enhancement you'd like to see.
      placeholder: Describe the feature here.
    validations:
      required: true
  - type: textarea
    id: why-feature
    attributes:
      label: Why do you think this feature is important?
      description: Explain why you believe this feature would be beneficial to the project.
      placeholder: Explain the importance of the feature.
    validations:
      required: true
  - type: textarea
    id: implementation-details
    attributes:
      label: Implementation Details (optional)
      description: If you have any ideas or suggestions on how this feature could be implemented, please share them here.
      placeholder: Share your implementation ideas (optional).
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Contribution Agreement
      description: By submitting this feature request, you agree to follow our [Contribution Agreement](https://example.com)
      options:
        - label: I agree to follow the Contribution Agreement
          required: true
