name: Stats Check

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

pull_request_rules:
  - name: Automatically merge when GitHub Actions jobs succeed
    conditions:
       - check-success=changelog_sync
       - check-success=actionlint
       - check-success=docker-onpremise
       - check-success=docker-saas
       - check-success=docker-label
       - check-success=add-linear-author-as-reviewer
    actions:
      merge:
        method: merge
